"""
streamlit_app.py
------------------
Interactive demo for the LLM-based support ticket auto-tagging system.

Run with:
    streamlit run app/streamlit_app.py

Lets a user paste ticket text, pick zero-shot / few-shot / both, and see
the top-3 predicted categories with confidence scores, plus a comparison
chart. Also shows the offline evaluation results (accuracy/F1/etc.) if
`results/metrics.json` has already been generated by src/main.py.
"""

import sys
import json
from pathlib import Path

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

sys.path.append(str(Path(__file__).resolve().parent.parent))

from src.config import CATEGORIES, RESULTS_DIR
from src import zero_shot_classifier as zsc
from src import few_shot_classifier as fsc

st.set_page_config(page_title="Support Ticket Auto-Tagger", page_icon="🎫", layout="wide")

st.title("🎫 LLM-Based Support Ticket Auto-Tagging")
st.caption("Zero-shot vs Few-shot classification with HuggingFace Transformers")

with st.sidebar:
    st.header("Settings")
    method = st.radio("Classification method", ["Zero-shot", "Few-shot", "Compare both"])
    shots = st.slider("Few-shot examples per category", 1, 2, 1)
    st.markdown("---")
    st.markdown("**Categories**")
    for c in CATEGORIES:
        st.markdown(f"- {c}")

st.subheader("Classify a ticket")
default_text = "My package tracking hasn't updated in 5 days and it still hasn't arrived."
ticket_text = st.text_area("Paste support ticket text:", value=default_text, height=120)

run_btn = st.button("Classify ticket", type="primary")


def render_ranking(title: str, ranked: list):
    st.markdown(f"**{title}**")
    df = pd.DataFrame(ranked)
    df["score"] = df["score"].round(3)
    st.dataframe(df, use_container_width=True, hide_index=True)

    fig, ax = plt.subplots(figsize=(5, 2.5))
    ax.barh(df["label"][::-1], df["score"][::-1], color="#4C72B0")
    ax.set_xlim(0, 1)
    ax.set_xlabel("Confidence")
    plt.tight_layout()
    st.pyplot(fig)


if run_btn and ticket_text.strip():
    with st.spinner("Classifying..."):
        if method in ("Zero-shot", "Compare both"):
            zs_result = zsc.classify_ticket(ticket_text, top_k=3)
        if method in ("Few-shot", "Compare both"):
            fs_result = fsc.classify_ticket(ticket_text, shots_per_category=shots, top_k=3)

    if method == "Compare both":
        col1, col2 = st.columns(2)
        with col1:
            render_ranking("Zero-shot top-3", zs_result)
        with col2:
            render_ranking("Few-shot top-3", fs_result)
    elif method == "Zero-shot":
        render_ranking("Zero-shot top-3", zs_result)
    else:
        render_ranking("Few-shot top-3", fs_result)

elif run_btn:
    st.warning("Please paste some ticket text first.")

st.markdown("---")
st.subheader("Offline evaluation results")

metrics_path = RESULTS_DIR / "metrics.json"
fig_path = RESULTS_DIR / "figures" / "metric_comparison.png"

if metrics_path.exists():
    with open(metrics_path) as f:
        metrics = json.load(f)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Zero-shot Accuracy", f"{metrics['zero_shot']['accuracy']:.2%}")
    col2.metric("Few-shot Accuracy", f"{metrics['few_shot']['accuracy']:.2%}")
    col3.metric("Zero-shot F1 (macro)", f"{metrics['zero_shot']['f1_macro']:.2%}")
    col4.metric("Few-shot F1 (macro)", f"{metrics['few_shot']['f1_macro']:.2%}")

    if fig_path.exists():
        st.image(str(fig_path), caption="Zero-shot vs Few-shot performance comparison")
else:
    st.info(
        "No evaluation results found yet. Run `python -m src.main` first to generate "
        "results/metrics.json and the comparison charts."
    )
